/*
 SELECT L_NAME, START_DATE, EMPL_ID
FROM EMPLOYEES E
JOIN JOB_HISTORY J ON E.EMP_ID = J.EMPL_ID
WHERE EMPL_ID = 5;
 */

/*
SELECT L_NAME, START_DATE, JOB_TITLE,  DEP_ID
FROM EMPLOYEES E
JOIN JOB_HISTORY J ON E.EMP_ID = J.EMPL_ID
JOIN JOBS J1 ON J1.JOB_IDENT = E.JOB_ID
WHERE DEP_ID = 5;
 */

/*
SELECT EMP_ID, L_NAME, B_DATE, DEPT_ID_DEP
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
WHERE YEAR(B_DATE) < 1980;
 */


SELECT F_NAME, L_NAME, DEP_NAME, DEPT_ID_DEP
FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP AND E.SEX = 'M';
