/*
SELECT *
FROM EMPLOYEES
WHERE DEP_ID = 5 AND (SALARY BETWEEN 60000 AND 70000);
*/

/*
 SELECT *
FROM EMPLOYEES
ORDER BY DEP_ID;
 */

/*
SELECT *
FROM EMPLOYEES
ORDER BY DEP_ID DESC,  L_NAME DESC;
 */

/*
SELECT COUNT(*) AS employee_count, DEP_ID
FROM EMPLOYEES
GROUP BY DEP_ID;
 */

/*
SELECT COUNT(*) AS employee_count, DEP_ID, AVG(SALARY) as avg_salary
FROM EMPLOYEES
GROUP BY DEP_ID;
 */

/*
SELECT COUNT(*) AS employee_count, DEP_ID, AVG(SALARY) as avg_salary
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) <4
ORDER BY avg_salary;
 */


SELECT *
FROM EMPLOYEES AS e
JOIN DEPARTMENTS AS d
ON e.DEP_ID = d.DEPT_ID_DEP
ORDER BY DEP_NAME DESC,  L_NAME DESC;
